### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by luca020400** [lineage-next/android_packages_apps_Twelve#18]
### Activity cards
- [x] Carousel list
  -  https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/416774

### Album
- [ ] Add all album's songs to playlist
- [x] Add all album's songs to queue
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/416776

### Artists
- [x] Display aware grid view instead of horizontal scroll list
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/416773
- [ ] Generate placeholder thumbnail using the name (match design specs)

### ID3 Editor
- [ ] Implement ID3 editor (at least album, year, artist and track name)
  - Will likely require some mapping from the MediaStorage item to the actual file, I don't know whether this is possible, need to investigate.

### Local Provider
- [ ] M3U Playlist import
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/415125
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/415126
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/415158
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/415160
- [x] Option to reset stats
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/416771
- [x] Delay play count increase after N seconds of playback (avoid counting immediately skipped tracks)
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/416772

### Other providers

- [ ] https://www.audiobookshelf.org/

### Main fragment
- [ ] Get rid of view pager
  - https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/415847

### Media session
- [ ] Make it non fallible

### Misc
- [x] Use album art as Audio thumbnail
  -  https://review.lineageos.org/c/LineageOS/android_packages_apps_Twelve/+/416775
- [x] Ensure state flows initialValue are sane
